swagger: "2.0"

info:
  title: Unofficial Cumplo API
  description: An independent API that unlocks the full potential of your Cumplo experience for smarter and faster investments with data-driven decision making and enhanced risk management
  version: 0.1.0

schemes:
  - https

produces:
  - application/json

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header

x-google-management:
  metrics:
    - name: cumplo-api-rate-limit
      displayName: Cumplo API Rate Limit
      valueType: INT64
      metricKind: DELTA

  quota:
    limits:
      - name: cumplo-api-quota
        metric: cumplo-api-rate-limit
        unit: 1/min/{project}
        values:
          STANDARD: 5

paths:
  "/funding-requests":
    get:
      operationId: getFundingRequests
      x-google-backend:
        address: https://cumplo-spotter-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

  "/funding-requests/promising":
    get:
      operationId: getPromisingFundingRequests
      x-google-backend:
        address: https://cumplo-spotter-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          description: API key
          required: true
          type: string
      responses:
        200:
          description: OK

  "/channels":
    get:
      operationId: getChannels
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

  "/channels/{channel_type}":
    get:
      operationId: getSingleChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: channel_type
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK

    post:
      operationId: postChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: channel_type
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        201:
          description: CREATED

  "/filters":
    get:
      operationId: getFilters
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

    post:
      operationId: postFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Filter"
      responses:
        201:
          description: CREATED

  "/filters/{id_filter}":
    get:
      operationId: getSingleFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id_filter
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK

    patch:
      operationId: patchFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id_filter
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Filter"
      responses:
        200:
          description: OK

    delete:
      operationId: deleteFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id_filter
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK

definitions:
  Channel:
    type: object
  Filter:
    type: object
