swagger: "2.0"

info:
  title: Unofficial Cumplo API
  description: An independent API that unlocks the full potential of your Cumplo experience for smarter and faster investments with data-driven decision making and enhanced risk management
  version: 1.1.0

schemes:
  - https

produces:
  - application/json

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header

x-google-management:
  metrics:
    - name: cumplo-api-rate-limit
      displayName: Cumplo API Rate Limit
      valueType: INT64
      metricKind: DELTA

  quota:
    limits:
      - name: cumplo-api-quota
        metric: cumplo-api-rate-limit
        unit: 1/min/{project}
        values:
          STANDARD: 5

paths:
  "/funding-requests":
    get:
      operationId: listFundingRequests
      x-google-backend:
        address: https://cumplo-spotter-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

  "/funding-requests/promising":
    get:
      operationId: listPromisingFundingRequests
      x-google-backend:
        address: https://cumplo-spotter-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          description: API key
          required: true
          type: string
      responses:
        200:
          description: OK

  "/funding-requests/{id}":
    get:
      operationId: retrieveFundingRequest
      x-google-backend:
        address: https://cumplo-spotter-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          description: API key
          required: true
          type: string
        - name: id
          in: path
          description: Funding request ID
          required: true
          type: string
      responses:
        200:
          description: OK

  "/users/me":
    delete:
      operationId: deleteUser
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        204:
          description: NO CONTENT

  "/users/me/disable":
    patch:
      operationId: disableUser
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        204:
          description: NO CONTENT

  "/channels":
    get:
      operationId: listChannels
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

  "/channels/{id}":
    get:
      operationId: retrieveChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
    
    delete:
      operationId: deleteChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: NO CONTENT

  "/channels/whatsapp":
    post:
      operationId: createWhatsappChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        201:
          description: CREATED

    patch:
      operationId: updateWhatsappChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        200:
          description: OK

  "/channels/webhook":
    post:
      operationId: createWebhookChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        201:
          description: CREATED

  "/channels/webhook/{id}":
    patch:
      operationId: updateWebhookChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        200:
          description: OK

  "/channels/ifttt":
    post:
      operationId: createIftttChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        201:
          description: CREATED

  "/channels/ifttt/{id}":
    patch:
      operationId: updateIftttChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        200:
          description: OK

  "/channels/{id}/events/{event}":
    post:
      operationId: enableChannelEvent
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
        - name: event
          in: path
          required: true
          type: string
      responses:
        201:
          description: CREATED
    
    delete:
      operationId: disableChannelEvent
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
        - name: event
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK

  "/filters":
    get:
      operationId: listFilters
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

    post:
      operationId: postFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Filter"
      responses:
        201:
          description: CREATED

  "/filters/{id}":
    get:
      operationId: retrieveFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK

    patch:
      operationId: patchFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Filter"
      responses:
        200:
          description: OK

    delete:
      operationId: deleteFilter
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          cumplo-api-rate-limit: 1
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK

definitions:
  Channel:
    type: object
  Filter:
    type: object
