swagger: "2.0"

info:
  title: Unofficial Cumplo API
  description: An independent API that unlocks the full potential of your Cumplo experience for smarter and faster investments with data-driven decision making and enhanced risk management
  version: 0.0.1

schemes:
  - https

produces:
  - application/json

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header

paths:
  "/funding-requests":
    get:
      operationId: getFundingRequests
      x-google-backend:
        address: https://cumplo-spotter-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

  "/funding-requests/promising":
    get:
      operationId: getPromisingFundingRequests
      x-google-backend:
        address: https://cumplo-spotter-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      parameters:
        - name: x-api-key
          in: header
          description: API key
          required: true
          type: string
      responses:
        200:
          description: OK

  "/channels":
    get:
      operationId: getChannels
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
      responses:
        200:
          description: OK

  "/channels/{channel_type}":
    get:
      operationId: getSingleChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: channel_type
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK

    post:
      operationId: postChannel
      x-google-backend:
        address: https://cumplo-tailor-ryugxhk4ca-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      parameters:
        - name: x-api-key
          in: header
          required: true
          type: string
        - name: channel_type
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Channel"
      responses:
        201:
          description: CREATED

definitions:
  Channel:
    type: object
